### ISSUE TITLE
wird nur einmal ausgeführ wegen "return": nur eine richtung wird bedacht

### ISSUE THREAD

**Issue by ninja67349** [ninja6734/reinforcementLearningCheckers#1]
```
        #TODO: wird nur einmal ausgeführ wegen "return": nur eine richtung wird bedacht
```

https://github.com/ninja6734/reinforcementLearningCheckers/blob/5fe532fa1d58d02a8b3d8676dce2517e6db5347d/try%201/test2.py#L21

**Comment by ninja6734** [comment]
fixed in 5a3498fc1e5986ace1ad2958bca2e8e4f6cf5d28
